language: node_js

notifications:
  email: false

node_js:
  - '12'

script:
  - npm run build

branches:
  only:
    - master

deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $LEMON_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
